### ISSUE TITLE
Clocks showing wrong time

### ISSUE THREAD

**Issue by JakubHolovsky** [mcmastermind/jClocksGMT#3]
Hello,

we are using your plugin and it seems to be showing wrong results. We are using version 1.1. When I alert new Date() it shows the correct time, please refer to the images below to show the wrong results.

JavaScript:

			$(document).ready(function(){
			var currentURL = $(location).attr('href');
			if (currentURL .toLowerCase().indexOf("_layouts") >= 0 || currentURL .toLowerCase().indexOf("_catalogs") >= 0)
			{
				$('#clock-rotator').hide();
			}
			else
			{
				$('#slider-stage').carousel('#previous', '#next');
				$('#viewport').carousel('#simplePrevious', '#simpleNext');   
	
				$('#clock_auckland').jClocksGMT({offset: '+12'});
	            $('#clock_elgin').jClocksGMT({offset: '-6'});
				$('#clock_la').jClocksGMT({offset: '-8'});
				$('#clock_pont').jClocksGMT({offset: '+1'});
				$('#clock_mougins').jClocksGMT({offset: '+1'});
				$('#clock_argenteuil').jClocksGMT({offset: '+1'});
				$('#clock_seongnam').jClocksGMT({offset: '+9'});
				$('#clock_toda').jClocksGMT({offset: '+9'});
				$('#clock_banalore').jClocksGMT({offset: '+5.5'});
				$('#clock_taipei').jClocksGMT({offset: '+8'});
				$('#clock_beijing').jClocksGMT({offset: '+8'});
				$('#clock_shenzhen').jClocksGMT({offset: '+8'});	
			}				
				
		});

Html:

			<a id="simplePrevious">Previous</a>
			<div id="viewport">
				<ul>
					<li>
		                <div id="clock_auckland" class="clock_container">
		                    <div class="lbl">Auckland</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		                <div id="clock_elgin" class="clock_container">
		                    <div class="lbl">Elgin</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_la" class="clock_container">
		                    <div class="lbl">Los Angeles</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_pont" class="clock_container">
		                    <div class="lbl">Pont-Sainte-Marie</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_mougins" class="clock_container">
		                    <div class="lbl">Mougins</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_argenteuil" class="clock_container">
		                    <div class="lbl">Argenteuil</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_seongnam" class="clock_container">
		                    <div class="lbl">Seongnam</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_toda" class="clock_container">
		                    <div class="lbl">Toda</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_banalore" class="clock_container">
		                    <div class="lbl">Banalore</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_taipei" class="clock_container">
		                    <div class="lbl">Taipei</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_beijing" class="clock_container">
		                    <div class="lbl">Beijing</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
		            <li>
		        		<div id="clock_shenzhen" class="clock_container">
		                    <div class="lbl">Shenzhen</div>            
		                    <div class="digital">
		                        <span class="hr"></span><span class="minute"></span> <span class="period"></span>
		                    </div>
		                </div>
		            </li>
				</ul>
			</div>

			<a id="simpleNext">Next</a>

Result:

![image](https://f.cloud.github.com/assets/4558405/2466353/82b1cdc4-afae-11e3-8fda-2d89d5472051.png)

Current time in Auckland (taken one minute after the first screen - the minutes are all correct):

![image](https://f.cloud.github.com/assets/4558405/2466357/94b43ef8-afae-11e3-84d5-77d07c03c663.png)

Thank you!

**Comment by bakman2** [comment]
I think something goes wrong here:

       var offset = options.offset;
should be:

      var offset = parseFloat(options.offset);

When the offset is "-" the calculation fails.
I have modified the script a bit for myself; added option dst true/false per clock and added seconds.

        (function($) {

    $.fn.extend({
        
        jClocksGMT: function(options) {
            
            var defaults = {
                offset: '0', // default gmt offset
                angleSec: 0,
                angleMin: 0,
                angleHour: 0,
                hour24: true,
                digital: true,
                dst:true
                
            }
            
            var options = $.extend(defaults, options);
            
            return this.each(function(){
                var offset = parseFloat(options.offset);
                var id = $(this).attr('id');

                // check if daylight saving time is in effect
                Date.prototype.stdTimezoneOffset = function() {
                    var jan = new Date(this.getFullYear(), 0, 1);
                    var janUTC = jan.getTime() + (jan.getTimezoneOffset() * 60000);
                    var janOffset = new Date(janUTC + (3600000 * options.offset));
                    var jul = new Date(this.getFullYear(), 6, 1);
                    var julUTC = jul.getTime() + (jul.getTimezoneOffset() * 60000);
                    var julOffset = new Date(julUTC + (3600000 * options.offset));
                    return Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset());
                   
                }
                Date.prototype.dst = function() {

                    if(options.dst){
                        var dCheck = new Date;
                        var utcCheck = dCheck.getTime() + (dCheck.getTimezoneOffset() * 60000);
                        var newCheck = new Date(utcCheck + (3600000 * options.offset));
                        return this.getTimezoneOffset() < this.stdTimezoneOffset();
                    }
                }
                // create new date object
                var dateCheck = new Date;

                if( dateCheck.dst() ) {
                    var offsetcheck = (options.offset.indexOf("-")==0) ? offset = offset : offset = offset + 1;

                };
                
                setInterval(function () {
                    var d = new Date;
                    var utc = d.getTime() + (d.getTimezoneOffset() * 60000);
 
                    var nd = new Date(utc + (3600000 * offset));
                    
                    var s = nd.getSeconds();
                    var m = nd.getMinutes();
                    var hh = nd.getHours();
                    var h = hh;
                    
                    if(!options.hour24) {
                        var dd = "AM";
                        if( h >= 12) {
                            h = hh-12;
                            dd = "PM";
                        }
                        if( h == 0 ) {
                            h = 12;
                        }
                    }
                    
                    if(options.digital) {
                        $('#' + id + ' .digital .hr').html(h + ':');
                        $('#' + id + ' .digital .minute').html(m < 10 ? "0" + m+":" : m +":");
                        $('#' + id + ' .digital .second').html(s < 10 ? "0" + s : s);

                    }
                }, 1000);
            });
        }
    });
       })(jQuery);

note that I have taken out the analog stuff as I don't need them.
now when I use the following they are displaying correctly (originally they didn't):

        $('#clock_washington').jClocksGMT({offset: '-4',dst:true});
        $('#clock_india').jClocksGMT({offset: '+5.5',dst:false});

I am still not sure if everything is correct when exiting out of dst.
